djangodonas/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    
    path('admin/', admin.site.urls, name="admin"),
    path('',include('tienda.urls'))
]

tienda/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('index', views.index, name='index'),
    path('admin/', views.admin, name='admin'),
    path('carrito/', views.carrito, name='carrito'),
    path('rellenas/', views.rellenas, name='rellenas'),
    path('glaseadas/', views.glaseadas, name='glaseadas'),
    path('bombon/', views.bombon, name='bombon'),
    path('chispas/', views.chispas, name='chispas'),
    path('nutella/', views.nutella, name='nutella'),
    path('contact/', views.contact_view, name='Contact'),
    path('login/',LoginView.as_view(template_name='tienda/login.html'),name="login"),
    path('registro/', views.registro, name='registro'),
    path('agregar_producto/<producto_id>/', views.agregar_producto, name='agregar_producto'),
    path('borrar_producto/<producto_id>/', views.borrar_producto, name='borrar_producto'),
    path('limpiar/', views.limpiar_carrito, name='limpiar_carrito'),
    path('ver_carrito/', views.ver_carrito, name='ver_carrito'),
    path('finalizar',views.finalizar , name= "finalizar"),
    
]




 

tienda/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.

class Categoria(models.Model):
    id = models.IntegerField(primary_key=True)
    nombre=models.CharField(default="default", max_length=50)
    definicion=models.TextField(blank=True)
    def __str__(self):
        return self.nombre
    


class Producto(models.Model):
    id = models.IntegerField(primary_key=True)
    stock = models.IntegerField(default=1)
    nombre =models.CharField(max_length=50)
    precio=models.IntegerField(null=True)
    precioEuro=models.FloatField(default="0.0")
    Categoria=models.ForeignKey(Categoria,on_delete=models.CASCADE)
    srcImagen = models.CharField(default="Imagen",max_length=400)
    def __str__(self):
        return self.nombre
    



class Contact(models.Model):
    name= models.CharField(max_length= 50, verbose_name="Nombre y Apellido")
    email=models.EmailField(unique=True,max_length=100, verbose_name="Correo Electrónico")
    message=models.CharField(max_length=250, verbose_name="Mensaje")
    options = [
    [0, 'Queja por un producto'],
    [1, 'Felicitaciones']

]
    contact_type = models.IntegerField(choices=options, verbose_name="Tipo de contacto")
    subscription = models.BooleanField(default=False, verbose_name= "Suscribirme para más información")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')
    
    

      


    def __str__(self) :
        return self.name 
    



class Venta(models.Model):
    usuario = models.ForeignKey(to=User, on_delete = models.CASCADE)
    fecha = models.DateTimeField(default=datetime.now, blank=True)
    total = models.IntegerField()

    def __str__(self):
        return f"{self.id} {self.usuario.username} {self.fecha}"

class DetalleVenta(models.Model):
    producto = models.ForeignKey(to=Producto, on_delete=models.CASCADE)
    venta = models.ForeignKey(to=Venta, on_delete=models.CASCADE)
    precio = models.IntegerField()
    cantidad = models.IntegerField()

    def __str__(self):
        return f"{self.venta.id} { self.producto.nombre}"

tienda/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Contact

class ContactForm(forms.ModelForm):
    name = forms.CharField(
        label='Nombre y Apellido',
        required=True,
        min_length=5,
        max_length=25,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Introduzca sus datos'})
    )
    email = forms.EmailField(
        label='Correo Electrónico',
        required=True,
        max_length=100,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Introduzca su email'})
    )
    message = forms.CharField(
        label='Mensaje',
        required=True,
        max_length=90,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Escriba aquí su mensaje...', 'rows': 5})
    )
    contact_type = forms.ChoiceField(
        label='Tipo de contacto',
        choices=[(0, 'Queja por un producto'), (1, 'Felicitaciones')],
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    subscription = forms.BooleanField(
        label='Suscribirme para más información',
        required=False,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input','id':'checkboxDiv'})
    )

    class Meta:
        model = Contact
        fields = ['name', 'email', 'message', 'contact_type', 'subscription']

class RegistroForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'input is-primary', 'placeholder': 'Correo Electrónico'})
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'password1': forms.PasswordInput(attrs={'class': 'input is-primary'}),
            'password2': forms.PasswordInput(attrs={'class': 'input is-primary'}),
            'username': forms.TextInput(attrs={'class': 'input is-primary', 'placeholder': 'Javiera'})
        }
        labels = {
            'username': 'Nombre de usuario',
            'email': 'Correo Electrónico',
            'password1': 'Contraseña',
            'password2': 'Confirmar contraseña'
        }

tienda/views.py
from django.shortcuts import render, redirect
from .models import Categoria, Producto, Contact, Venta, DetalleVenta
from .forms import ContactForm, RegistroForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db import transaction
import requests

# Create your views here.


@login_required
def agregar_producto(request, producto_id):
    euro = requests.get('https://mindicador.cl/api').json()
    valor = euro["euro"]["valor"]
    print(valor)
    if request.method == 'POST':
        carro = request.session.get('carro', [])
        producto = Producto.objects.get(id=producto_id)

        for item in carro:
            if item['id'] == producto_id:
                if item['cantidad'] < producto.stock:
                    item['cantidad'] += 1
                    item['total'] = item['precio'] * item['cantidad']
                    item['total2'] = item['precioEuro'] * item['cantidad']
                else:
                    
                    pass
                break
        else:
            if producto.stock > 0:
                carro.append({
                    'id': producto_id,
                    'categoria': producto.nombre,
                    'precio': producto.precio,
                    'precioEuro': producto.precio/valor,
                    'nombre': producto.nombre,
                    'src_image': producto.srcImagen,
                    'cantidad': 1,
                    'total': producto.precio * 1,
                    'total2': producto.precioEuro * 1
                })
            else:
                
                pass

        total_clp = sum(item['total'] for item in carro)
        total_euro = sum(item['total2'] for item in carro)

        request.session['carro'] = carro
        request.session['total_clp'] = total_clp
        request.session['total_euro'] = total_euro


        
        

        return redirect('ver_carrito')
    return redirect('ver_carrito')


@login_required
def ver_carrito(request): 
    context = {}
    carro = request.session.get('carro', [])
    total_clp = request.session.get('total_clp', 0)
    total_euro = request.session.get('total_euro', 0)

    context["carro"] = carro
    context["total_clp"] = total_clp
    context["total_euro"] = total_euro
    return render(request, 'tienda/carrito.html', context)


@login_required
def finalizar(request):
    carrito = request.session.get("carro", [])
    if len(carrito) == 0:
        return redirect(to="index")

    with transaction.atomic():
        venta = Venta(usuario=request.user, total=sum(item["total"] for item in carrito))
        venta.save()

        for item in carrito:
            producto = Producto.objects.get(id=item["id"])
            cantidad_a_comprar = min(item["cantidad"], producto.stock)

            detalle = DetalleVenta(
                venta=venta,
                producto=producto,
                cantidad=cantidad_a_comprar,
                precio=item["precio"]
            )
            detalle.save()

            producto.stock -= cantidad_a_comprar
            producto.save()

    del request.session["carro"]
    return redirect(to="carrito")


@login_required
def borrar_producto(request, producto_id):
    if request.method == 'POST':
        carro = request.session.get('carro', [])
        carro = [item for item in carro if item['id'] != producto_id]

        total_clp = sum(item['total'] for item in carro)
        total_euro = sum(item['total2'] for item in carro)

        request.session['carro'] = carro
        request.session['total_clp'] = total_clp
        request.session['total_euro'] = total_euro

        return redirect('ver_carrito')
    return redirect('ver_carrito')


@login_required
def limpiar_carrito(request):
    if request.method == 'POST':
        request.session['carro'] = []
        request.session['total_clp'] = 0
        request.session['total_euro'] = 0
        return redirect('ver_carrito')
    return redirect('ver_carrito')


def registro(request):
    if request.method == 'POST':
        registro = RegistroForm(request.POST)
        if registro.is_valid():
            registro.save()
            return redirect(to='login')
    else:
        registro = RegistroForm()

    return render(request, 'tienda/registro.html', {'form': registro})


@login_required
def index(request):
    return render(request, 'tienda/index.html')


def inicio(request):
    return render(request, 'tienda/iniciodetodo.html')


@login_required
def carrito(request):
    return render(request, 'tienda/carrito.html')


@login_required
def admin(request):
    return render(request, 'tienda/index.html')


@login_required
def rellenas(request):
    productos = Producto.objects.filter(Categoria=1)

    for producto in productos:
        if producto.stock < 0:
            producto.stock = 0
            producto.save()

    contextRellenas = {"rellenas": productos}
    return render(request, 'tienda/rellenas.html', contextRellenas)


@login_required
def glaseadas(request):
    productos = Producto.objects.filter(Categoria=2).values()
    contextGlaseadas = {"glaseadas": productos}
    return render(request, 'tienda/glaseadas.html', contextGlaseadas)


@login_required
def bombon(request):
    productos = Producto.objects.filter(Categoria=3).values()
    contextBombon = {"bombon": productos}
    return render(request, 'tienda/bombon.html', contextBombon)


@login_required
def chispas(request):
    productos = Producto.objects.filter(Categoria=4).values()
    contextChispas = {"chispas": productos}
    return render(request, 'tienda/chispas.html', contextChispas)


@login_required
def nutella(request):
    productos = Producto.objects.filter(Categoria=5).values()
    contextNutella = {"nutella": productos}
    return render(request, 'tienda/nutella.html', contextNutella)


@login_required
def contact_view(request):
    contact_form = ContactForm()

    if request.method == 'POST':
        contact_form = ContactForm(data=request.POST)

        if contact_form.is_valid():
            contact_form.save()
            return redirect(reverse('Contact') + '?ok')
        else:
            return redirect(reverse('Contact') + '?error')

    messages = Contact.objects.all()

    return render(request, 'tienda/Contact.html', {'form': contact_form, 'messages': messages})

tienda/templates/tienda/bombon.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Deli'S Donuts - Donas Bombón</title>
  <link rel="stylesheet" href="{% static './css/productos.css' %}">
  <link rel="icon" type="image/png" href="{% static './images/iconopagina.png' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #ea97c3;">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">
          <img src="{% static './images/iconopagina.png' %}" alt="Logo" width="30" height="24"
            class="d-inline-block align-text-top">
          Doh-Donas
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rellenas' %}">Donas Rellenas</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'glaseadas' %}">Donas Glaseadas</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'bombon' %}">Donas Bombón</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'chispas' %}">Donas Chispas</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'nutella' %}">Donas Nutella</a>
            </li>
          </ul>
          <a class="button ms-auto" href="{% url 'inicio' %}">Cerrar Sesión</a>
          {% if user.is_authenticated %}
          <a class="navbar-item" href="{% url 'admin' %}">{{ user.username }}</a>
          {% endif %}
          <div class="content-carrito-icon">
            <nav class="content-carro">
              <a href="{% url 'carrito' %}">
                <img src="{% static './images/iconocarrito.png' %}" width="50px" height="50px">
              </a>
            </nav>
          </div>
        </div>
      </div>
    </nav>
  </header>

  <div class="container mt-4">
    <div class="row">
      {% for producto in bombon %}
      <div class="col-md-4 mb-4">
        <div class="card">
          <figure>
            <img src="{% static producto.srcImagen %}" class="card-img-top" alt="Producto">
          </figure>
          <div class="card-body" style="background-color: #39aedc">
            <h5 class="card-title" style="color: #fff">{{ producto.nombre }}</h5>
            <p class="card-text">Precio: $ {{ producto.precio }} CLP</p>
            <p class="card-text">Precio Euro: $ {{ producto.precioEuro }} EUR</p>
            <p class="card-text">Stock: {{ producto.stock }}</p>
            {% if producto.stock > 0 %}
            <button type="button2" style="background-color: #d4c53a !important" class="btn btn-primary3">
              ⇧
            </button>
            <form class="add-to-cart-form" action="{% url 'agregar_producto' producto.id %}" method="post">
              {% csrf_token %}
              <button type="button" style="background-color: #d4c53a !important" class="btn btn-primary4 add-to-cart-btn" data-producto-id="{{ producto.id }}">Añadir al carrito</button>
            </form>
            {% else %}
            <p class="btn btn-primary5" style="background-color: #989898 !important">Producto sin stock</p>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  {% for producto in bombon %}
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="cartModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="cartModalLabel">¡ {{ producto.nombre }} añadido correctamente!</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" style="text-align: center !important;">
          ─────────────•❥❥❥•───────────
        </div>
        <div class="modal-footer">
          <button type="button" style="background-color: #39aedc !important " class="btn btn-secondary" data-bs-dismiss="modal">Seguir comprando</button>
          <a href="{% url 'ver_carrito' %}" style="background-color: #39aedc !important " class="btn btn-primary">Ver carrito</a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}

  <footer class="footer">
    <div class="container">
      <div class="F-Contacto">
        <a href="{% url 'Contact' %}">
          <img src="{% static './images/fondofed123.jpg' %}" alt="" width="300" height="50">
        </a>
      </div>
      <div class="footer-links">
        <div class="link-img">
          <img src="" alt="">
          <div class="socials-2">
            <a href="#"><img src="{% static './images/r1.svg' %}" alt=""></a>
            <a href="#"><img src="{% static './images/r2.svg' %}" alt=""></a>
            <a href="#"><img src="{% static './images/r3.svg' %}" alt=""></a>
          </div>
          <div class="footer-copy">
            <h5>─────────────•❥❥❥•───────────</h5>
          </div>
        </div>
        <div class="link">
          <h3>Contacto</h3>
          <ul>
            <li><a href="#">m.@gmail.com</a></li>
            <li><a href="#">933556453</a></li>
            <li><a href="#">San Agustin #554, Melipilla, Santiago</a></li>
          </ul>
        </div>
        <div class="link">
          <h3>Más Populares</h3>
          <ul>
            <li><a href="{% url 'rellenas' %}">Donas Rellenas</a></li>
            <li><a href="{% url 'glaseadas' %}">Donas Glaseadas</a></li>
            <li><a href="{% url 'nutella' %}">Donas Nutella</a></li>
          </ul>
        </div>
        <div class="link">
          <h3>Informaciones</h3>
          <ul>
            <li><a href="#">Politica de privacidad</a></li>
            <li><a href="#">Términos y condiciones</a></li>
            <li><a href="#">Terminos de despacho</a></li>
          </ul>
        </div>
        <h6>© TODOS LOS DERECHOS RESERVADOS</h6>
      </div>
    </div>
  </footer>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
  <script src="{% static './js/modal.js' %}"></script>
  <!---<script src="{% static './js/index.js' %}"></script>-->
  <!---<script src="{% static './js/validarFormulario.js' %}"></script>-->

</body>

</html>

tienda/templates/tienda/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Deli'S Donuts - Contacto</title>
    <link rel="stylesheet" href="{% static './css/contacto.css' %}">
    <link rel="icon" type="png"  href="{% static './images/iconopagina.png '%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>

{% block content %}

<header>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #ea97c3;">
    <a class="navbar-brand" href="{% url 'index' %}">
      <img src="{% static './images/iconopagina.png '%}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
      Doh-Donas
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"><a class="nav-link" href="{% url 'rellenas' %}">Donas Rellenas</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'glaseadas' %}">Donas Glaseadas</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'bombon' %}">Donas Bombón</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'chispas' %}">Donas Chispas</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'nutella' %}">Donas Nutella</a></li>
      </ul>
      <a class="button ms-auto" href="{% url 'inicio' %}">Cerrar Sesión</a>
      {% if user.is_authenticated %}
      <a class="navbar-item" href="{% url 'admin' %}">{{ user.username }}</a>
      {% endif %}
      <div class="content-carrito-icon">
        <nav class="content-carro">
          <a href="{% url 'carrito' %}"><img src="{% static './images/iconocarrito.png '%}" width="50px" height="50px"></a>
        </nav>
      </div>
    </div>
  </nav>
</header>

<a class="button1" href="{% url 'index' %}">Volver Atrás</a>
<h3 class="text-center">Formulario de Contacto</h3>
<p class="fs-5 text-center px-5" style="color: #fff !important;">Es un placer que puedas contactarnos. Nos pondremos en contacto contigo, en el menor tiempo posible.</p>
<div class="row2">
  <div class="col-md-6">
    <form action="" method="POST">
      <div class="form-content">
        {% csrf_token %}
        {{ form }}
        <input class="btn btn-primary" type="submit" value="Enviar Mensaje" {% if 'ok' in request.GET %}disabled{% endif %}{% if 'error' in request.GET %}disabled{% endif %}>
      </div>
    </form>
    {% if 'ok' in request.GET %}
    <div class="alert alert-success mt-5" role="alert">
      <strong>El mensaje se ha enviado correctamente</strong>
    </div>
    {% endif %}
    {% if 'error' in request.GET %}
    <div class="alert alert-danger mt-5" role="alert">
      <strong>El mensaje no ha podido ser enviado. Por favor, intente mas tarde</strong>
    </div>
    {% endif %}
  </div>
  <div class="col-md-6 mb-5">
    <img class="float-start img-fluid" src="{% static '' %}" alt="">
  </div>
</div>

<hr>
<h3 class="text-center">Comentarios Recibidos</h3>

<div class="container mt-4">
  <div class="row">
    {% for message in messages %}
    <div class="col-md-4 mb-4">
      <div class="card">
        <div class="card-body" style="background-color: #e0d64c">
          <h5 class="card-title" style="color: #fff !important">
            <p><strong>Nombre:</strong> {{ message.name }}</p>
          </h5>
          <p class="card-text" style="color: #5adaeb"><strong>Correo Electrónico:</strong> {{ message.email }}</p>
          <p class="card-text" style="color: #5adaeb"><strong>Mensaje:</strong> {{ message.message }}</p>
          <p class="card-text" style="color: #5adaeb"><strong>Tipo de Contacto:</strong> {{ message.get_contact_type_display }}</p>
          <p class="card-text" style="color: #5adaeb"><strong>Suscripción:</strong> {{ message.subscription|yesno:"Sí,No" }}</p>
          <hr>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<footer class="footer">
  <div class="container">
    <div class="footer-links">
      <div class="link-img">
        <img src="" alt="">
        <div class="socials-2">
          <a href="#"><img src="{% static './images/r1.svg '%}" alt=""></a>
          <a href="#"><img src="{% static './images/r2.svg '%}" alt=""></a>
          <a href="#"><img src="{% static './images/r3.svg '%}" alt=""></a>
        </div>
        <div class="footer-copy">
          <h5>─────────────•❥❥❥•───────────</h5>             
        </div>
      </div>
      <div class="link">
        <h3>Contacto</h3>
        <ul>
          <li><a href="#">m.@gmail.com</a></li>
          <li><a href="#">933556453</a></li>
          <li><a href="#">San Agustin #554, Melipilla, Santiago</a></li>
        </ul>
      </div>
      <div class="link">
        <h3>Más Populares</h3>
        <ul>
          <li><a href="{% url 'rellenas' %}">Donas Rellenas</a></li>
          <li><a href="{% url 'glaseadas' %}">Donas Glaseadas</a></li>
          <li><a href="{% url 'nutella' %}">Donas Nutella</a></li>
        </ul>
      </div>
      <div class="link">
        <h3>Informaciones</h3>
        <ul>
          <li><a href="#">Politica de privacidad</a></li>
          <li><a href="#">Términos y condiciones</a></li>
          <li><a href="#">Terminos de despacho</a></li>
        </ul>
      </div>
      <h6>© TODOS LOS DERECHOS RESERVADOS</h6>
    </div>
  </div>
</footer>

{% endblock %}
{% load static %}
<!---<script src="{% static './js/index.js' %}"></script>-->
<!---<script src="{% static './js/validarFormulario.js' %}"></script>-->
</body>
</html>

tienda/templates/tienda/index.html
{% extends "base.html" %}
{% block title %}Deli'S Donuts - Inicio{% endblock %}
{% load static %}
{% block content %}

<div class="contenedor">
    <p>¿Quieres probar una deliciosa Doh-dona? Pues aquí en Delis-Donuts encontrarás las mejores donas, hechas con ingredientes frescos y de la más alta calidad. Disfruta de una amplia variedad de sabores, desde los clásicos glaseados hasta innovadoras combinaciones que te sorprenderán. Nuestras donas son perfectas para cualquier ocasión, ya sea para un antojo personal, una reunión con amigos o una celebración especial. Ven y descubre por qué nuestras donas son las favoritas de todos. ¡Te esperamos!</p>
</div>

<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleSlidesOnly" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleSlidesOnly" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleSlidesOnly" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'images/carrusel2opc4.jpg' %}" class="d-block w-100" alt="Imagen 1">
        </div>
        <div class="carousel-item">
            <img src="{% static 'images/carrousel1opc1.jpg' %}" class="d-block w-100" alt="Imagen 2">
        </div>
        <div class="carousel-item">
            <img src="{% static 'images/carrusel3opc1.jpg' %}" class="d-block w-100" alt="Imagen 3">
        </div>
    </div>
</div>

{% endblock %}

tienda/templates/tienda/iniciodetodo.html
<!DOCTYPE html>
<html lang="en">
<head>
   {% load static %}
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
   <title>Deli'S Donuts - Login</title>
   <link rel="icon" type="png" href="{% static './images/iconopagina.png '%}">
   <link rel="stylesheet" href="{% static './css/iniciodetodo.css' %}">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
   
</head>
<body>
    <header>  
        <nav class="navbar navbar-expand-lg navbar-dark " style="background-color: #ea97c3 ;">
            
            <a class="navbar-brand" href="#">
              <img src="{% static './images/iconopagina.png '%}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
             Doh-Donas
            </a>
       
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
             data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
             aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
               <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                     <a class="nav-link" href="#">Donas Rellenas</a>
                    </li>
                    <li class="nav-item">
                     <a class="nav-link" href="#">Donas Glaseadas</a>
                    </li>
                    <li class="nav-item">
                     <a class="nav-link" href="#">Donas Bombón </a>
                    </li>
                    <li class="nav-item">
                     <a class="nav-link" href="#">Donas Chispas</a>
                    </li>
                    <li class="nav-item">
                     <a class="nav-link" href="#">Donas Nutella</a>
                    </li>
                </ul>

                    <a class="button" href="{% url 'login' %}">Iniciar Sesión</a>
                    <a class="button" href="{% url 'registro' %}">Registrarse</a>
            </div>
        </nav>
    </header>
    
</body>
</html>